### ISSUE TITLE
기말프로젝트 깃허브 주소

### ISSUE THREAD

**Issue by Junnie-Jobs** [NHNNEXT/2015-02-HTML5#124]
임동준
https://github.com/Junnie-Jobs/HTML5_Project

**Comment by itooolsg** [comment]
최연규
https://github.com/daybrush/scenejs

**Comment by mixed** [comment]
@itooolsg 
https://www.w3.org/TR/web-animations/ 이거 한번 봐바

**Comment by skychb** [comment]
변치호 
https://github.com/skychb/HTML5_project

**Comment by mixed** [comment]
명찬
https://github.com/Paul-Kim/LaosMedicalChart

**Comment by mixed** [comment]
https://github.com/Byeol/NextDrop

**Comment by skychb** [comment]
[](https://github.com/skychb/HTML5_project/blob/master/HTML5PT.pdf)
발표 자료

**Comment by skychb** [comment]
https://github.com/skychb/HTML5_project/blob/master/HTML5PT.pdf
발표자료

**Comment by Junnie-Jobs** [comment]
https://github.com/Junnie-Jobs/HTML5_Project/blob/master/%EB%B0%9C%ED%91%9C%EC%9E%90%EB%A3%8C%20pdf.pdf
발표자료

**Comment by mixed** [comment]
@Junnie-Jobs @itooolsg @skychb @Byeol @Paul-Kim

모두 수고했다.
